---
debug: true


azure_location: 'eastus'
azure_resource_group_name: 'tju-example-rg'
azure_storage_account: 'tjuexample00007' # must not contain '-'
azure_resource_vm_name: 'tju-test-vm'
azure_vm_size: 'Standard_D2s_v3'
azure_admin_username: 'tjungbauer'
ssh_key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCpjgLkditWo8/2SDY5AsQ2Las8Md8m4TbefzBoIM0AD9xRCnhGqMG9rf23D/l4ABj/VNyqoQ0rFYLRI4RGAY+bSLZrYzz0CInzhJ2A/wH5gHeEzM5D3WjiuQ9q6rOfl0zBxZetRW0QU8Lp2+0dOZ+GD74p+oB8XbLj5Q0viWEt6vtZjd0uRWSIkW7E7Bv5OURV2brSw6o9OEjyFK4Dtkt0Hd3lsVQVTKn785wyH5Gnpsdgeh/zbvHax4VVuIclbn5iqC/xH9bA77AMiXip7Jd+52yCDDUK/qkwUmYNKX9j/Q0IqMrigH3arhpJ+iKKq2KG28Y0UP7dJ9fbugCKw4v'

os_packages_add:
  - cronie-anacron
  - rsyslog

os_packages_remove: 
  - httpd 
  - dhcp
  - bind
  - dovecot
  - openldap-servers
  - samba
  - squid
  - telnet-server
  - tftp
  - vsftpd
  - xorg-x11-server-common
  - xinetd
  - ypbind
  - ypserv

# sshd_settings
sshd_protocol: 2 
sshd_ignore_rhosts: 'yes'

# 5.4.1
cis_pass_max_days: 90
cis_pass_min_days: 7
cis_pass_warn_age: 7
cis_pass_inactive_lock: 30

# 5.4.2
cis_skip_lock_users:
  - root
  - halt
  - shutdown
  - sync

# 5.4.4
cis_umask_default: "027"
cis_umask_shell_files:
- /etc/bashrc
- /etc/profile

sap_preconfigure_modify_etc_hosts: yes
sap_domain: 'ispworld.at'
