---
- name: Get facts of a VM
  hosts: localhost
  connection: local
  become: false
  gather_facts: false

  tasks: 

  #- name: Destroy Azure Deploy
  #  azure_rm_deployment:
  #    resource_group: tju-ResourceGroup
  #    name: tju-testDeployment
  #    state: absent

  - name: Create Azure Resource Group deployment
    azure_rm_deployment:
      state: present
      resource_group_name: tju-ResourceGroup
      name: tju-testDeployment
      #template_link: 'https://raw.githubusercontent.com/tjungbauer/auto/master/test.json'
      template: "{{ lookup('file', 'ResourceManagerTemplate.json') }}"
      parameters:
        projectName:
          value: tjuProject
        location:
          value: "East US"
        adminUsername:
          value: tjungbauer
        adminPublicKey:
          value: "{{ lookup('file', '/Users/tjungbauer/.ssh/id_rsa.pub') }}"
        operatingSystem:
          value: CentOS
        operatingSystemPublisher:
          value: OpenLogic
        operatingSystemSKU:
          value: '7.1'
        vmSize:
          value: Standard_D2s_v3
    register: azure

  - name: Add new instance to host group
    add_host:
      hostname: "{{ item['ips'][0].public_ip }}"
      groupname: azure_vms
    loop: "{{ azure.deployment.instances }}"
