---
- name: Get facts of a VM
  hosts: localhost
  connection: local
  become: false
  gather_facts: false

  tasks: 
  - name: Get facts of a VM
    azure_rm_virtualmachine_info:
      resource_group: "{{azure_resource_group_name}}" 
    register: facts_vm

  - name: DEBUG Get facts of a VM
    debug:
      var: facts_vm
    when: debug|bool == true